on:
  push:

jobs:
  install:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: ${{ github.repository }}

      - name: install
        run: |
          yarn --frozen-lockfile
      - name: build
        uses: no-yan/matrix-reusable-workflow/.github/workflows/use-build.yml@main
      - name: test
        run: |
          yarn test
